"""add status and due_date to tasks

Revision ID: 80cf4ec0aa61
Revises: ba1292040e9c
Create Date: 2026-08-11 14:32:55.438305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cf4ec0aa61'
down_revision: Union[str, Sequence[str], None] = 'ba1292040e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('todos', sa.Column('due_date', sa.String(length=110), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
